# Generated by Django 3.0.8 on 2020-07-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='value_of_items_purchased_before',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
